// Mock job data - Jobs from job posters
export const mockJobs = [
  // From English Training Center Poster (Keystone)
  {
    id: 1,
    title: 'English Teachers',
    company: 'Keystone',
    location: 'Galle',
    posted: '2025/11/20',
    logo: '/images/poster/hiringPoster1.png',
    poster: '/images/poster/hiringPoster1.png',
    email: 'keystone.info.lk@gmail.com',
    contact: '+94 70 250 97 32',
  },
  {
    id: 2,
    title: 'Trainee Teachers',
    company: 'Keystone',
    location: 'Galle',
    posted: '2025/11/20',
    logo: '/images/poster/hiringPoster1.png',
    poster: '/images/poster/hiringPoster1.png',
    email: 'keystone.info.lk@gmail.com',
    contact: '+94 70 250 97 32',
  },
  {
    id: 3,
    title: 'Coordinators',
    company: 'Keystone',
    location: 'Galle',
    posted: '2025/11/20',
    logo: '/images/poster/hiringPoster1.png',
    poster: '/images/poster/hiringPoster1.png',
    email: 'keystone.info.lk@gmail.com',
    contact: '+94 70 250 97 32',
  },
  // From Accounting Positions Poster
  {
    id: 4,
    title: 'Assistant Accountant',
    company: 'Company Name Withheld',
    location: 'Colombo',
    posted: '2025/12/07',
    logo: '/images/poster/secondJobPost.jpeg',
    poster: '/images/poster/secondJobPost.jpeg',
    email: 'hr@financesolutions.lk',
    contact: '+94 171 78 54 243',
  },
  {
    id: 5,
    title: 'Accounts Executives',
    company: 'Company Name Withheld',
    location: 'Colombo',
    posted: '2025/12/07',
    logo: '/images/poster/secondJobPost.jpeg',
    poster: '/images/poster/secondJobPost.jpeg',
    email: 'hr@financesolutions.lk',
    contact: '+94 71 78 54 243',
  },
  {
    id: 6,
    title: 'Senior Tax Accountant',
    company: 'Company Name Withheld',
    location: 'WFH',
    posted: '2025/12/10',
    logo: '/images/poster/post3.jpeg',
    poster: '/images/poster/post3.jpeg',
    email: 'bpo.sl.jobs.@gmail.com',
    contact: '',
  },
//   {
//     id: 7,
//     title: 'Accounts Executives',
//     company: 'Finance Solutions',
//     location: 'Colombo',
//     posted: '2025/12/07',
//     logo: '/images/poster/secondJobPost.jpeg',
//     poster: '/images/poster/post3.jpeg',
//     email: 'hr@financesolutions.lk',
//     contact: '+94 11 234 5678',
//   },
];

